version: '3'
services:
  mq:
    image: dubc/rabbitmq-alpine-all-plugins:latest
    environment:
      RABBITMQ_DEFAULT_PASS: enterra
      RABBITMQ_DEFAULT_USER: enterra
    ports:
    - 5671:5671/tcp
    - 5672:5672/tcp
    - 15671:15671/tcp
    - 15672:15672/tcp
    - 15674:15674/tcp
